// Generated by tools/sync_api_schema.py. Do not edit by hand.
import type { GraphUiState, GroupEditorState } from './route-graph'

export type Position3 = [number, number, number]

export interface GraphNode {
  id: string
  name: string
  position: Position3
  yaw_hint: number | null
  tags: string[]
  meta: Record<string, unknown>
}

export interface GraphEdge {
  id: string
  from: string
  to: string
  weight: number
  enabled: boolean
  bidirectional: boolean
  meta: Record<string, unknown>
}

export interface RouteGraph {
  schema_version: number
  env_id: string
  graph_name: string
  default_altitude: number | null
  nodes: GraphNode[]
  edges: GraphEdge[]
  meta: Record<string, unknown>
}

export interface GraphSummary {
  path: string
  file_name: string
  graph_name: string
  env_id: string
  node_count: number
  edge_count: number
  enabled_edge_count: number
  group_colors: string[]
  bridge_count: number
  is_legacy: boolean
  updated_at: string
  load_error?: string
}

export interface GraphEnvelope {
  path: string
  summary: GraphSummary
  graph: RouteGraph
  ui_state?: GraphUiState
  group_editor_state?: GroupEditorState
}

export interface ValidationIssue {
  severity: 'error' | 'warning' | string
  code: string
  message: string
  refs: string[]
}

export interface ValidationReport {
  is_valid: boolean
  error_count: number
  warning_count: number
  issues: ValidationIssue[]
}

export interface RouteEdgePass {
  pass_index: number
  edge_id: string
  from_node: string
  to_node: string
  segment_index: number
  local_index: number
}

export interface RouteSegment {
  start_anchor: string
  end_anchor: string
  node_ids: string[]
  edge_ids: string[]
  edge_passes: RouteEdgePass[]
  length: number
  meta: Record<string, unknown>
}

export interface RouteCandidate {
  candidate_id: string
  rank: number
  planned_nodes: string[]
  edge_passes: RouteEdgePass[]
  segments: RouteSegment[]
  total_length: number
  selected: boolean
  meta: Record<string, unknown>
}

export interface RouteCandidateSet {
  evaluation_version: number
  env_id: string
  graph_name: string
  anchor_nodes: string[]
  candidates: RouteCandidate[]
  node_lookup: Record<string, GraphNode>
  selected_candidate_ids: string[]
  meta: Record<string, unknown>
}

export interface AutoPlanJobProgress {
  phase: string
  pairs_considered: number
  max_pairs_to_evaluate: number
  valid_pairs_found: number
  candidate_pool_size: number
  selected_routes: number
  max_output_routes: number
  done: boolean
  searched_candidates: number
  filtered_candidates: number
  kept_candidates: number
  progress_kind: 'auto'
}

export interface AutoPlanJobStatus {
  job_id: number
  graph: string
  state: 'running' | 'succeeded' | 'failed' | 'cancelled' | 'timed_out'
  progress: AutoPlanJobProgress | null
  candidate_set: RouteCandidateSet | null
  error: string | null
  started_at: string
  updated_at: string
  finished_at: string | null
}

export interface GraphCatalogResponse {
  default_graph: string
  graphs: GraphSummary[]
}

export interface CandidateSaveResponse {
  path: string
  graph_name: string
  candidate_count: number
  selected_candidate_ids: string[]
}

export interface MissionExportResponse {
  output_dir: string
  requested_candidate_ids: string[]
  succeeded: string[]
  failed: string[]
  written_files: Record<string, string>
  errors: Record<string, string>
}

export type MissionPositionState = [Position3, [number, number, number]]

export interface MissionPosition {
  state: MissionPositionState
  time: number
  frame: number
  image_path: string
  info?: Record<string, unknown>
}

export interface MissionRouteMeta {
  candidate_id?: string
  candidate_rank?: number
  total_length?: number
  edge_pass_count?: number
  turn_smoothing_enabled?: boolean
  corner_turn_count?: number
  u_turn_count?: number
  smoothing_fallback_count?: number
  [key: string]: unknown
}

export interface MissionPreview {
  positions: MissionPosition[]
  route_meta?: MissionRouteMeta
  [key: string]: unknown
}

export interface MissionPreviewResponse {
  candidate_id: string
  mission: MissionPreview
}

export interface AddEdgeRequest {
  graph?: string | null
  from_node: string
  to_node: string
  bidirectional?: boolean
  edge_kind?: string | null
  group_color?: string | null
}

export interface DataDirHealth {
  path: string
  writable: boolean
}

export interface ExportMissionsRequest {
  step_distance?: number
  fps?: number
  altitude_mode?: string
  fixed_z?: number | null
  altitude_offset?: number
  takeoff_landing_relative_z?: number | null
  takeoff_landing_step_distance?: number | null
  node_sample_radius?: number
  random_seed?: number | null
  turn_smoothing_enabled?: boolean
  corner_radius?: number
  small_turn_yaw_blend_threshold_deg?: number
  corner_min_angle_deg?: number
  u_turn_threshold_deg?: number
  u_turn_transition_distance?: number
  corner_max_yaw_step_deg?: number
  u_turn_pivot_yaw_step_deg?: number
  candidate_set: Record<string, unknown>
  output_dir?: string | null
  candidate_ids?: string[]
  candidate_id?: string | null
}

export interface FrontendDistHealth {
  path: string
  exists: boolean
  index_exists: boolean
}

export interface GenerateAutoPlanRequest {
  graph?: string | null
  max_output_routes?: number
  max_routes_per_pair?: number
  max_anchor_pairs_to_evaluate?: number
  min_frame_count?: number | null
  max_frame_count?: number | null
  distance_per_frame?: number
  min_total_length?: number | null
  max_total_length?: number | null
  max_edge_pass_factor?: number
  max_search_states?: number
  min_endpoint_distance?: number
  prefer_connected_anchors?: boolean
  prefer_route_diversity?: boolean
  allow_reverse_direction_counterparts?: boolean
  coverage_weight?: number
  diversity_weight?: number
  anchor_weight?: number
  reverse_penalty_weight?: number
  node_coverage_weight?: number
  endpoint_reuse_weight?: number
  allowed_route_group_colors?: string[]
  excluded_endpoint_group_colors?: string[]
  export_config?: Record<string, unknown> | null
}

export interface GeneratePlanRequest {
  graph?: string | null
  start_node: string
  end_node: string
  via_nodes?: string[]
  max_routes?: number
  max_edge_pass_factor?: number
  min_total_length?: number | null
  max_total_length?: number | null
  min_frame_count?: number | null
  max_frame_count?: number | null
  export_config?: Record<string, unknown> | null
}

export interface GraphStoreHealth {
  root: string
  count: number
}

export interface HTTPValidationError {
  detail?: ValidationError[]
}

export interface HealthResponse {
  status: string
  version: string
  frontend_dist: FrontendDistHealth
  data_dir: DataDirHealth
  graphs: GraphStoreHealth
  workers: Record<string, WorkerServiceHealth>
}

export interface NodeMoveRequest {
  graph?: string | null
  node_id: string
  x: number
  y: number
}

export interface NodeUpdateRequest {
  graph?: string | null
  node_id: string
  name?: string | null
  tags?: string[] | null
  yaw_hint?: number | null
  sample_radius?: number | null
}

export interface PreviewMissionRequest {
  step_distance?: number
  fps?: number
  altitude_mode?: string
  fixed_z?: number | null
  altitude_offset?: number
  takeoff_landing_relative_z?: number | null
  takeoff_landing_step_distance?: number | null
  node_sample_radius?: number
  random_seed?: number | null
  turn_smoothing_enabled?: boolean
  corner_radius?: number
  small_turn_yaw_blend_threshold_deg?: number
  corner_min_angle_deg?: number
  u_turn_threshold_deg?: number
  u_turn_transition_distance?: number
  corner_max_yaw_step_deg?: number
  u_turn_pivot_yaw_step_deg?: number
  candidate_set: Record<string, unknown>
  candidate_id: string
}

export interface RemoveEdgeBetweenRequest {
  graph?: string | null
  from_node: string
  to_node: string
}

export interface RemoveEdgeRequest {
  graph?: string | null
  edge_id: string
}

export interface SaveCandidateSetRequest {
  candidate_set: Record<string, unknown>
  file_name?: string | null
}

export interface ScopedGraphRequest {
  graph?: string | null
}

export interface UpdateCanvasViewRequest {
  graph?: string | null
  rotation_quadrants?: number
  flip_horizontal?: boolean
  flip_vertical?: boolean
}

export interface UpdateEdgeRequest {
  graph?: string | null
  edge_id: string
  enabled?: boolean | null
  bidirectional?: boolean | null
  edge_kind?: string | null
  group_color?: string | null
}

export interface UpdateGraphGroupConfigRequest {
  graph?: string | null
  group_color?: string | null
  group_config?: Record<string, unknown>
  bridge_color?: string | null
}

export interface UpdateGraphUiStateRequest {
  graph?: string | null
  planner_inputs?: Record<string, unknown>
  group_inputs?: Record<string, unknown>
  auto_plan_inputs?: Record<string, unknown>
  export_inputs?: Record<string, unknown>
}

export interface ValidationError {
  loc: (string | number)[]
  msg: string
  type: string
  input?: unknown
  ctx?: Record<string, unknown>
}

export interface WorkerServiceHealth {
  worker_path: string
  worker_exists: boolean
  runtime_root: string
  active_jobs: number
  jobs_by_state?: Record<string, number>
}

export type MissionConfigPayload = Pick<PreviewMissionRequest, "step_distance" | "fps" | "altitude_mode" | "fixed_z" | "altitude_offset" | "takeoff_landing_relative_z" | "takeoff_landing_step_distance" | "node_sample_radius" | "random_seed" | "turn_smoothing_enabled" | "corner_radius" | "small_turn_yaw_blend_threshold_deg" | "corner_min_angle_deg" | "u_turn_threshold_deg" | "u_turn_transition_distance" | "corner_max_yaw_step_deg" | "u_turn_pivot_yaw_step_deg">
export type AutoPlanRequestPayload = GenerateAutoPlanRequest
export type GeneratePlanPayload = Omit<GeneratePlanRequest, 'export_config'> & { export_config?: MissionConfigPayload | null }
export type SaveCandidateSetPayload = Omit<SaveCandidateSetRequest, 'candidate_set'> & { candidate_set: RouteCandidateSet }
export type ExportMissionsPayload = Omit<ExportMissionsRequest, 'candidate_set'> & { candidate_set: RouteCandidateSet }
export type PreviewMissionPayload = Omit<PreviewMissionRequest, 'candidate_set'> & { candidate_set: RouteCandidateSet }
