from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Mapping


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = PROJECT_ROOT / "webui_frontend" / "src" / "types" / "api-contract.schema.json"
TS_PATH = PROJECT_ROOT / "webui_frontend" / "src" / "types" / "api-contract.ts"
CONFIG_EXCLUDE_KEYS = {"candidate_set", "candidate_id", "candidate_ids", "output_dir"}


def _load_openapi_contract() -> dict[str, Any]:
    if str(PROJECT_ROOT) not in sys.path:
        sys.path.insert(0, str(PROJECT_ROOT))
    from webui_backend.server import app

    schema = app.openapi()
    return {
        "openapi": schema.get("openapi"),
        "info": schema.get("info"),
        "paths": schema.get("paths", {}),
        "components": {"schemas": schema.get("components", {}).get("schemas", {})},
    }


def _format_json(payload: dict[str, Any]) -> str:
    return json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def _schema_ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def _ts_type(schema: Mapping[str, Any] | None) -> str:
    if not isinstance(schema, dict):
        return "unknown"
    if "$ref" in schema:
        return _schema_ref_name(str(schema["$ref"]))
    if "anyOf" in schema:
        parts = [_ts_type(part) for part in schema["anyOf"]]
        unique_parts: list[str] = []
        for part in parts:
            if part not in unique_parts:
                unique_parts.append(part)
        return " | ".join(unique_parts)
    if "enum" in schema and isinstance(schema["enum"], list):
        return " | ".join(json.dumps(value) for value in schema["enum"])

    schema_type = schema.get("type")
    if schema_type == "null":
        return "null"
    if schema_type == "string":
        return "string"
    if schema_type in {"number", "integer"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "array":
        item_type = _ts_type(schema.get("items"))
        if " | " in item_type:
            item_type = f"({item_type})"
        return f"{item_type}[]"
    if schema_type == "object":
        properties = schema.get("properties")
        if isinstance(properties, dict) and properties:
            required = set(schema.get("required") or [])
            parts = []
            for name, property_schema in properties.items():
                optional = "" if name in required else "?"
                parts.append(f"{json.dumps(name)}{optional}: {_ts_type(property_schema)}")
            return "{ " + "; ".join(parts) + " }"
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"Record<string, {_ts_type(additional)}>"
        return "Record<string, unknown>"
    return "unknown"


def _render_component_types(contract: dict[str, Any]) -> list[str]:
    schemas = contract.get("components", {}).get("schemas", {})
    lines: list[str] = []
    for name in sorted(schemas):
        schema = schemas[name]
        if not isinstance(schema, dict):
            continue
        if schema.get("type") != "object":
            lines.append(f"export type {name} = {_ts_type(schema)}")
            lines.append("")
            continue

        properties = schema.get("properties") if isinstance(schema.get("properties"), dict) else {}
        required = set(schema.get("required") or [])
        lines.append(f"export interface {name} {{")
        if not properties:
            lines.append("  [key: string]: unknown")
        for property_name, property_schema in properties.items():
            optional = "" if property_name in required else "?"
            lines.append(f"  {property_name}{optional}: {_ts_type(property_schema)}")
        lines.append("}")
        lines.append("")
    return lines


def _mission_config_keys(contract: dict[str, Any]) -> tuple[str, ...]:
    preview_schema = contract.get("components", {}).get("schemas", {}).get("PreviewMissionRequest", {})
    properties = preview_schema.get("properties") if isinstance(preview_schema, dict) else {}
    if not isinstance(properties, dict):
        return ()
    return tuple(key for key in properties if key not in CONFIG_EXCLUDE_KEYS)


def _render_ts(contract: dict[str, Any]) -> str:
    mission_keys = _mission_config_keys(contract)
    mission_pick = " | ".join(json.dumps(key) for key in mission_keys) or "never"
    lines = [
        "// Generated by tools/sync_api_schema.py. Do not edit by hand.",
        "import type { GraphUiState, GroupEditorState } from './route-graph'",
        "",
        "export type Position3 = [number, number, number]",
        "",
        "export interface GraphNode {",
        "  id: string",
        "  name: string",
        "  position: Position3",
        "  yaw_hint: number | null",
        "  tags: string[]",
        "  meta: Record<string, unknown>",
        "}",
        "",
        "export interface GraphEdge {",
        "  id: string",
        "  from: string",
        "  to: string",
        "  weight: number",
        "  enabled: boolean",
        "  bidirectional: boolean",
        "  meta: Record<string, unknown>",
        "}",
        "",
        "export interface RouteGraph {",
        "  schema_version: number",
        "  env_id: string",
        "  graph_name: string",
        "  default_altitude: number | null",
        "  nodes: GraphNode[]",
        "  edges: GraphEdge[]",
        "  meta: Record<string, unknown>",
        "}",
        "",
        "export interface GraphSummary {",
        "  path: string",
        "  file_name: string",
        "  graph_name: string",
        "  env_id: string",
        "  node_count: number",
        "  edge_count: number",
        "  enabled_edge_count: number",
        "  group_colors: string[]",
        "  bridge_count: number",
        "  is_legacy: boolean",
        "  updated_at: string",
        "  load_error?: string",
        "}",
        "",
        "export interface GraphEnvelope {",
        "  path: string",
        "  summary: GraphSummary",
        "  graph: RouteGraph",
        "  ui_state?: GraphUiState",
        "  group_editor_state?: GroupEditorState",
        "}",
        "",
        "export interface ValidationIssue {",
        "  severity: 'error' | 'warning' | string",
        "  code: string",
        "  message: string",
        "  refs: string[]",
        "}",
        "",
        "export interface ValidationReport {",
        "  is_valid: boolean",
        "  error_count: number",
        "  warning_count: number",
        "  issues: ValidationIssue[]",
        "}",
        "",
        "export interface RouteEdgePass {",
        "  pass_index: number",
        "  edge_id: string",
        "  from_node: string",
        "  to_node: string",
        "  segment_index: number",
        "  local_index: number",
        "}",
        "",
        "export interface RouteSegment {",
        "  start_anchor: string",
        "  end_anchor: string",
        "  node_ids: string[]",
        "  edge_ids: string[]",
        "  edge_passes: RouteEdgePass[]",
        "  length: number",
        "  meta: Record<string, unknown>",
        "}",
        "",
        "export interface RouteCandidate {",
        "  candidate_id: string",
        "  rank: number",
        "  planned_nodes: string[]",
        "  edge_passes: RouteEdgePass[]",
        "  segments: RouteSegment[]",
        "  total_length: number",
        "  selected: boolean",
        "  meta: Record<string, unknown>",
        "}",
        "",
        "export interface RouteCandidateSet {",
        "  evaluation_version: number",
        "  env_id: string",
        "  graph_name: string",
        "  anchor_nodes: string[]",
        "  candidates: RouteCandidate[]",
        "  node_lookup: Record<string, GraphNode>",
        "  selected_candidate_ids: string[]",
        "  meta: Record<string, unknown>",
        "}",
        "",
        "export interface AutoPlanJobProgress {",
        "  phase: string",
        "  pairs_considered: number",
        "  max_pairs_to_evaluate: number",
        "  valid_pairs_found: number",
        "  candidate_pool_size: number",
        "  selected_routes: number",
        "  max_output_routes: number",
        "  done: boolean",
        "  searched_candidates: number",
        "  filtered_candidates: number",
        "  kept_candidates: number",
        "  progress_kind: 'auto'",
        "}",
        "",
        "export interface AutoPlanJobStatus {",
        "  job_id: number",
        "  graph: string",
        "  state: 'running' | 'succeeded' | 'failed' | 'cancelled' | 'timed_out'",
        "  progress: AutoPlanJobProgress | null",
        "  candidate_set: RouteCandidateSet | null",
        "  error: string | null",
        "  started_at: string",
        "  updated_at: string",
        "  finished_at: string | null",
        "}",
        "",
        "export interface GraphCatalogResponse {",
        "  default_graph: string",
        "  graphs: GraphSummary[]",
        "}",
        "",
        "export interface CandidateSaveResponse {",
        "  path: string",
        "  graph_name: string",
        "  candidate_count: number",
        "  selected_candidate_ids: string[]",
        "}",
        "",
        "export interface MissionExportResponse {",
        "  output_dir: string",
        "  requested_candidate_ids: string[]",
        "  succeeded: string[]",
        "  failed: string[]",
        "  written_files: Record<string, string>",
        "  errors: Record<string, string>",
        "}",
        "",
        "export type MissionPositionState = [Position3, [number, number, number]]",
        "",
        "export interface MissionPosition {",
        "  state: MissionPositionState",
        "  time: number",
        "  frame: number",
        "  image_path: string",
        "  info?: Record<string, unknown>",
        "}",
        "",
        "export interface MissionRouteMeta {",
        "  candidate_id?: string",
        "  candidate_rank?: number",
        "  total_length?: number",
        "  edge_pass_count?: number",
        "  turn_smoothing_enabled?: boolean",
        "  corner_turn_count?: number",
        "  u_turn_count?: number",
        "  smoothing_fallback_count?: number",
        "  [key: string]: unknown",
        "}",
        "",
        "export interface MissionPreview {",
        "  positions: MissionPosition[]",
        "  route_meta?: MissionRouteMeta",
        "  [key: string]: unknown",
        "}",
        "",
        "export interface MissionPreviewResponse {",
        "  candidate_id: string",
        "  mission: MissionPreview",
        "}",
        "",
        *_render_component_types(contract),
        f"export type MissionConfigPayload = Pick<PreviewMissionRequest, {mission_pick}>",
        "export type AutoPlanRequestPayload = GenerateAutoPlanRequest",
        "export type GeneratePlanPayload = Omit<GeneratePlanRequest, 'export_config'> & { export_config?: MissionConfigPayload | null }",
        "export type SaveCandidateSetPayload = Omit<SaveCandidateSetRequest, 'candidate_set'> & { candidate_set: RouteCandidateSet }",
        "export type ExportMissionsPayload = Omit<ExportMissionsRequest, 'candidate_set'> & { candidate_set: RouteCandidateSet }",
        "export type PreviewMissionPayload = Omit<PreviewMissionRequest, 'candidate_set'> & { candidate_set: RouteCandidateSet }",
        "",
    ]
    return "\n".join(lines)


def _read_current(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return None


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Sync the backend OpenAPI contract for the WebUI frontend.")
    parser.add_argument("--check", action="store_true", help="Fail if the checked-in schema or DTO file is stale")
    args = parser.parse_args(argv)

    contract = _load_openapi_contract()
    rendered_schema = _format_json(contract)
    rendered_ts = _render_ts(contract)
    if args.check:
        current_schema = _read_current(SCHEMA_PATH)
        current_ts = _read_current(TS_PATH)
        if current_schema is None or current_ts is None:
            print(f"Missing API contract outputs under {SCHEMA_PATH.parent}", file=sys.stderr)
            return 1
        if current_schema != rendered_schema or current_ts != rendered_ts:
            print(
                "API schema/DTO contract is stale. Run `python tools/sync_api_schema.py`.",
                file=sys.stderr,
            )
            return 1
        return 0

    SCHEMA_PATH.parent.mkdir(parents=True, exist_ok=True)
    SCHEMA_PATH.write_text(rendered_schema, encoding="utf-8")
    TS_PATH.write_text(rendered_ts, encoding="utf-8")
    print(f"Wrote {SCHEMA_PATH.relative_to(PROJECT_ROOT).as_posix()}")
    print(f"Wrote {TS_PATH.relative_to(PROJECT_ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
